spring:
  datasource:
    # MySQL 데이터베이스 연결 설정
    url: jdbc:mysql://192.168.219.101:3306/zb-payment-study?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8  # 데이터베이스 접속 URL
    username: root                # 데이터베이스 접속 사용자명
    password: 6188               # 데이터베이스 접속 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버 클래스명

  jpa:
    # Hibernate 설정
    hibernate:
      ddl-auto: update          # 데이터베이스 스키마 자동 업데이트 설정
    show-sql: true              # SQL 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true        # SQL 쿼리 포맷팅 활성화
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 문법 사용
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 데이터베이스 플랫폼 지정

# JWT 설정
jwt:
  secret: your_jwt_secret_key   # JWT 토큰 생성/검증용 비밀키
  expiration: 86400000          # JWT 토큰 만료시간 (24시간, 밀리초 단위)