spring:
  datasource:
    url: jdbc:mysql://192.168.219.101:3306/zb-payment-study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 6188
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
        connection:
          provider_disables_autocommit: false
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: yourSecretKeyHereMustBeAtLeast32BytesLong
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
