spring:
  datasource:
    # MySQL 데이터베이스 연결 설정
    url: ${DB_URL} # 데이터베이스 접속 URL
    username: ${DB_USERNAME} # 데이터베이스 접속 사용자명
    password: ${DB_PASSWORD} # 데이터베이스 접속 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스명

  jpa:
    # Hibernate 설정
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트 설정
    show-sql: true # SQL 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅 활성화
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 문법 사용
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect # 데이터베이스 플랫폼 지정

# JWT 설정
jwt:
  secret: your_jwt_secret_key # 실제 운영 환경에서는 환경 변수로 관리 필요
  expiration: 86400000 # JWT 토큰 만료시간 (24시간, 밀리초 단위)

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
    # 추가 모니터링 지표 설정 필요
  endpoint:
    health:
      show-details: always
